version: 2
jobs:
  build:
    working_directory: ~/coalmine
    
    docker:
      - image: circleci/ruby:2.3.4
      - image: circleci/postgres:9.5-alpine
        
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          key: coalmine-v2-{{ checksum "Gemfile.lock" }}

      # Set up the environment
      - run: |
          set -xu
          # Install node and psql
          sudo apt-get install -y nodejs postgresql-client
          # Install our database user - necessary for db:structure:load
          createuser -h localhost -U root -s circleci
          # Update bundler
          gem install bundler
        
      # Install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: coalmine-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Database setup
      - run: |
          set -xu
          mv config/database-ci.yml config/database.yml
          bundle exec rake db:create
          bundle exec rake db:structure:load

      # Run rspec in parallel
      - run: |
          set -xu
          touch app/assets/javascripts/main.bundle.js
          mkdir -p tmp/test-results
          bundle exec rake test TESTOPTS="--ci-dir=tmp/test-results" $(circleci tests glob "test/**/*_test.rb" | circleci tests split --split-by=timings)

      # Stash results
      - store_test_results:
          path: tmp/test-results
