defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: circleci
  database: circle_test

development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults
