development:
  canary:
    uri: 'http://localhost:4000/api/v1'
test:
  canary:
    uri: 'http://localhost:4000/api/v1'
staging:
  canary:
    uri: 'http://localhost:8081/api/v1'
production:
  canary:
    uri: 'http://localhost:8081/api/v1'
