development:
  canary:
    uri: 'http://localhost:4000/api/v1'
test:
  canary:
    uri: 'http://localhost:4000/api/v1'
staging:
  canary:
    uri: 'http://localhost/api/v1'
production:
  canary:
    uri: 'https://localhost/api/v1'
