development:
  rubysec:
    domains:
      - rubysec.dev

test:
  rubysec:
    domains:
      - rubysec.dev


staging:
  rubysec:
    domains:
      - rubysec.staging.appcanary.com

production:
  rubysec:
    domains:
      - rubysec.com
