class PrefOpt
  EMAIL_FREQ_DAILY = "daily"
  EMAIL_FREQ_BOTH = "both"
  EMAIL_FREQ_FIRE = "firehose"
  EMAIL_FREQ_NEVER = "never"

  EMAIL_WANTS_DAILY = [EMAIL_FREQ_DAILY, EMAIL_FREQ_BOTH]
  EMAIL_WANTS_FIREHOSE = [EMAIL_FREQ_FIRE, EMAIL_FREQ_BOTH]
end
